name: Feature Request
description: I need to change the way something works, or create a new feature.
title: "[Feature Request] : "
labels: ["bug", "triage"]
  - damen-dotcms
body:
- type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Fill in the role, action, and benefit.
      placeholder: As a ___, I want ___, in order to ___.
      value: TODO
    validations:
      required: true
