blank_issues_enabled: false
contact_links:
  - name: Looking for Customer Support?
    url: https://www.dotcms.com/contact-us/
    about: Feel free to use the Support Portal if you are an existing customer. 
