name: Feature

description: I need to change the way something works, or create new functionality. 

labels: ['Type - Feature']

assignees:
  - damen-dotcms

body:

  - type: markdown
    attributes:
      value: |
        If you have any questions about how to use this form, check out [How dotCMS uses GitHub](https://docs.google.com/presentation/d/1C1oCESIL9Z84xXo1DPWQZh48c4BSGlVRAn1DYGEFMUw).

  - type: textarea
    id: user-story
    attributes:
      label: "User Story"
      description: "As a ___, I want to be able to ___, so I can ___."
      placeholder:
      value: 
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria 
    attributes:
      label: "Acceptance Criteria"
      description: "What objective needs to be met in order to resolve this?"
      placeholder: 
      value: 
    validations:
      required: true

  - type: textarea
    id: external-links 
    attributes:
      label: "External Links... Slack Conversations, Support Tickets, Figma Designs, etc."
      description: "Provide links to any support tickets or Slack conversations that help explain the problem or desired outcome."
      placeholder: 
      value: 
    validations:
      required: false

  - type: textarea
    id: assumptions
    attributes:
      label: "Assumptions & Initiation Needs"
      description: "List relevant assumptions, pre-requisite steps, or issues that need to be completed before this issue can be worked on."
      placeholder:
      value: 
    validations:
      required: false

  - type: textarea
    id: sub-tasks
    attributes:
      label: "Sub-Tasks"
      description: "Use a task-list format, and feel free to @ people responsible for completion."
      placeholder: |
        - [ ] Some Task Related to this Issue
        - [ ] Some Task for Damen @damen-dotcms        
      value:
    validations:
      required: false
      
  - type: textarea
    id: estimates
    attributes:
      label: "Estimates"
      description: "Used by development team."
      placeholder:
      value:
    validations:
      required: false
      
  - type: dropdown
    id: proposed-objective
    attributes:
      label: "Proposed Objective"
      description: 
      options:
        - "Please Select"
        - "Application Performance"
        - "Code Maintenance"
        - "Core Features"
        - "Customer Retention"
        - "Customer Success"
        - "Customer Support"
        - "Developer Experience"
        - "DevOps Experience"
        - "Documentation"
        - "Integration Support"
        - "Marketing"
        - "Quality Assurance"
        - "Sales"
        - "Scalability"
        - "Security"
        - "Training"
        - "User Experience"
    validations:
      required: true

  - type: dropdown
    id: proposed-prioritiy
    attributes:
      label: "Proposed Priority"
      description: 
      options:
        - "Please Select"
        - "Priority 1 - Show Stopper"
        - "Priority 2 - Important"
        - "Priority 3 - Average"
        - "Priority 4 - Trivial"
    validations:
      required: true
