name: New Feature
description: I need to change the way something works, or create a new feature.
title: "[New Functionality] : "
labels: ['Type - New Functionality']
body:
  - type: dropdown
    id: proposed-objective
    attributes:
      label: What broad business objective does this fall under?
      options:
        - Application Performance
        - Core Improvement
        - Developer Experience
        - Documentation
        - Maintenance
        - Retention
        - Sales
        - Security 
    validations:
      required: true

  - type: dropdown
    id: proposed-prioritiy
    attributes:
      label: How important is this request?
      options:
        - Priority - 1 Show Stopper
        - Priority - 2 Important
        - Priority - 3 Average
        - Priority - 4 Low
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Fill in the role, action, and benefit.
      placeholder: As a ___, I want ___, in order to ___.
      value: TODO
    validations:
      required: true
