name: Task

description: I just need to create a simple to-do for someone on the team.

title: "[Task]: "

labels: ['Type - Task']

assignees:
  - damen-dotcms

body:

  - type: dropdown
    id: proposed-objective
    attributes:
      label: "Proposed Objective"
      description: "If you have any questions about how to categorize this work, please check the [documentation](https://docs.google.com/presentation/d/1C1oCESIL9Z84xXo1DPWQZh48c4BSGlVRAn1DYGEFMUw)."
      options:
        - "Same As Parent"
        - "Accessibility (WCAG)"
        - "Application Performance"
        - "Core Improvement (Features)"
        - "Customer Acquisition"
        - "Customer Success"
        - "Developer Experience"
        - "Documentation"
        - "Integration Support"
        - "Maintenance"
        - "Quality Assurance"
        - "Scalability"
        - "Security"
        - "User Experience"
    validations:
      required: true

  - type: dropdown
    id: proposed-prioritiy
    attributes:
      label: "Proposed Priority"
      options:
        - "Same As Parent"
        - "Priority 1 - Show Stopper"
        - "Priority 2 - Important"
        - "Priority 3 - Average"
        - "Priority 4 - Trivial"
    validations:
      required: true

  - type: textarea
    id: parent-issue
    attributes:
      label: "Parent Issue"
      description: "Please include a GitHub issue link to the parent issue."
      placeholder:
      value: 
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria 
    attributes:
      label: "Acceptance Criteria"
      description: "What objective needs to be met in order to resolve this?"
      placeholder: 
      value: 
    validations:
      required: false

  - type: textarea
    id: external-links 
    attributes:
      label: "External Links"
      description: "Provide links to any support tickets or Slack conversations that help explain the problem or desired outcome."
      placeholder: 
      value: 
    validations:
      required: false

  - type: textarea
    id: wireframes-designs-prototypes
    attributes:
      label: "Wireframes, Designs, or Prototypes"
      description: "Provide links to any Figma files."
      placeholder:
      value: 
    validations:
      required: false

  - type: textarea
    id: assumptions
    attributes:
      label: "Assumptions & Initiation Needs"
      description: "List relevant assumptions, pre-requisite steps, or issues that need to be completed before this issue can be worked on."
      placeholder:
      value: 
    validations:
      required: false

  - type: textarea
    id: estimates
    attributes:
      label: "Estimates"
      description: "Used by development team."
      placeholder:
      value:
    validations:
      required: false
      
  - type: textarea
    id: tasks
    attributes:
      label: "Sub-Tasks"
      description: "Used by development team when creating estimates. Please use a task-list format."
      placeholder: 
      value:
    validations:
      required: false
